# Generated by Django 5.0.4 on 2024-06-01 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_compte', models.CharField(max_length=25)),
                ('numero_operateur', models.CharField(max_length=20)),
                ('solde', models.FloatField(default=0)),
                ('bloque', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise')),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('compte_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_destination', to='banque.comptebancaire')),
                ('compte_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_source', to='banque.comptebancaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
