# Generated by Django 5.0.4 on 2024-06-17 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banque', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementechoue',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.checkout'),
        ),
        migrations.AddField(
            model_name='paiementreussi',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.checkout'),
        ),
        migrations.AddField(
            model_name='retrait',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banque.comptebancaire'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_destination', to='banque.comptebancaire'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_source', to='banque.comptebancaire'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
