# Generated by Django 5.0.4 on 2024-04-04 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=150)),
                ('description', models.TextField(verbose_name="Description de l'entreprise")),
                ('logo', models.ImageField(upload_to='')),
                ('pays', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('secteur_activiter', models.CharField(max_length=150)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_compte', models.CharField(max_length=150)),
                ('solde', models.FloatField(default=0, verbose_name="solde du compte de l'entreprise")),
                ('operation', models.CharField(max_length=15, verbose_name='retrait/depot')),
                ('bloque', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Signaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.compte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signaler',
                'verbose_name_plural': 'Signalers',
            },
        ),
    ]
