# Generated by Django 5.0.4 on 2024-04-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaler',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='signaler',
            name='user',
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
        migrations.DeleteModel(
            name='Signaler',
        ),
    ]
