# Generated by Django 5.0.4 on 2024-04-04 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField(max_length=500)),
                ('delais', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Acce',
                'verbose_name_plural': 'Acces',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('image_presentation', models.ImageField(upload_to='')),
                ('gratuit', models.BooleanField(default=False)),
                ('prix_produit', models.FloatField()),
                ('prix_produit_promotion', models.FloatField(null=True)),
                ('langue_produit', models.CharField(max_length=25)),
                ('categorie_produit', models.CharField(max_length=150)),
                ('taille_Fichier', models.IntegerField()),
                ('supprime', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produits.produit')),
                ('auteur', models.CharField(max_length=150)),
                ('nombre_page', models.IntegerField()),
                ('editeur', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
            bases=('produits.produit',),
        ),
        migrations.CreateModel(
            name='ProduitNumerique',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produits.produit')),
                ('type', models.CharField(max_length=50, verbose_name='Pour specifier le type de document')),
            ],
            options={
                'verbose_name': 'Produit Numerique',
                'verbose_name_plural': 'Produit Numeriques',
            },
            bases=('produits.produit',),
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
