# Generated by Django 5.0.4 on 2024-04-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='editeur',
        ),
    ]
