# Generated by Django 5.0.4 on 2024-04-22 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_livre_auteur_remove_livre_editeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acce',
            name='id',
        ),
        migrations.AddField(
            model_name='acce',
            name='produit_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produits.produit'),
            preserve_default=False,
        ),
    ]
