# Generated by Django 5.0.4 on 2024-09-04 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('produits', '0002_visite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit de OPM', 'verbose_name_plural': 'Tous les produits de OPM'},
        ),
        migrations.AddField(
            model_name='checkout',
            name='prix_client',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='prix_produit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='taux',
            field=models.FloatField(default=10.0),
        ),
        migrations.CreateModel(
            name='VisiteMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.GenericIPAddressField(verbose_name='IP Client')),
                ('region', models.CharField(max_length=150, null=True, verbose_name='Région')),
                ('pays', models.CharField(max_length=150, null=True, verbose_name='Pays')),
                ('ville', models.CharField(max_length=150, null=True, verbose_name='Ville')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de Visite')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise', verbose_name='Entreprise')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Visite Multiple',
                'verbose_name_plural': 'Visites Multiples',
            },
        ),
    ]
