# Generated by Django 5.0.4 on 2024-04-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_remove_acce_id_acce_produit_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(),
        ),
    ]
