# Generated by Django 5.0.4 on 2024-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_alter_produit_date_alter_produit_date_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
