# Generated by Django 5.0.4 on 2024-04-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_signaler_compte_remove_signaler_user_and_more'),
        ('produits', '0008_alter_produit_date_alter_produit_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise'),
        ),
    ]
